#include "ganim/animation/animation.hpp"
#include "ganim/animation/creation.hpp"
#include "ganim/animation/fading.hpp"
#include "ganim/animation/indicate.hpp"
#include "ganim/animation/scaling.hpp"
#include "ganim/animation/transform.hpp"
#include "ganim/animation/color_stack.hpp"
